# Copyright (c) 2013, Teo Mrnjavac <teo@kde.org>

include(FindPackageHandleStandardArgs)

if( NOT BUILD_WITH_QT4 )
    find_package(TelepathyQt5 NO_MODULE)
    set(TelepathyQt_FOUND ${TelepathyQt5_FOUND})
    set(TELEPATHY_QT_VERSION ${TELEPATHY_QT5_VERSION})
    set(TELEPATHY_QT_INSTALL_DIR ${TELEPATHY_QT5_INSTALL_DIR})
    set(TELEPATHY_QT_INCLUDE_DIR ${TELEPATHY_QT5_INCLUDE_DIR})
    set(TELEPATHY_QT_LIB_DIR ${TELEPATHY_QT5_LIB_DIR})
    set(TELEPATHY_QT_SHARE_DIR ${TELEPATHY_QT5_SHARE_DIR})
    set(TELEPATHY_QT_LIBRARIES ${TELEPATHY_QT5_LIBRARIES})
else()
    find_package(TelepathyQt4 NO_MODULE)
    set(TelepathyQt_FOUND ${TelepathyQt4_FOUND})
    set(TELEPATHY_QT_VERSION ${TELEPATHY_QT4_VERSION})
    set(TELEPATHY_QT_INSTALL_DIR ${TELEPATHY_QT4_INSTALL_DIR})
    set(TELEPATHY_QT_INCLUDE_DIR ${TELEPATHY_QT4_INCLUDE_DIR})
    set(TELEPATHY_QT_LIB_DIR ${TELEPATHY_QT4_LIB_DIR})
    set(TELEPATHY_QT_SHARE_DIR ${TELEPATHY_QT4_SHARE_DIR})
    set(TELEPATHY_QT_LIBRARIES ${TELEPATHY_QT4_LIBRARIES})
endif()

set(TELEPATHY_QT_FOUND ${TelepathyQt_FOUND})

find_package_handle_standard_args(TelepathyQt DEFAULT_MSG  TELEPATHY_QT_INSTALL_DIR )
