# Copyright (c) 2013, Teo Mrnjavac <teo@kde.org>

include(FindPackageHandleStandardArgs)

find_package(TelepathyQt5 NO_MODULE)
set(TelepathyQt_FOUND ${TelepathyQt5_FOUND})
set(TELEPATHY_QT_VERSION ${TELEPATHY_QT5_VERSION})
set(TELEPATHY_QT_INSTALL_DIR ${TELEPATHY_QT5_INSTALL_DIR})
set(TELEPATHY_QT_INCLUDE_DIR ${TELEPATHY_QT5_INCLUDE_DIR})
set(TELEPATHY_QT_LIB_DIR ${TELEPATHY_QT5_LIB_DIR})
set(TELEPATHY_QT_SHARE_DIR ${TELEPATHY_QT5_SHARE_DIR})
set(TELEPATHY_QT_LIBRARIES ${TELEPATHY_QT5_LIBRARIES})

set(TELEPATHY_QT_FOUND ${TelepathyQt_FOUND})

find_package_handle_standard_args(TelepathyQt DEFAULT_MSG  TELEPATHY_QT_INSTALL_DIR )
